### ISSUE TITLE
Teardown atomicity (models AND observers)

### ISSUE THREAD

**Issue by srlessard** [NASA-Tensegrity-Robotics-Toolkit/NTRTsim#102]
Do we at some point want to create an atomic method in tgSubject that calls both the onTeardown and the notifyTeardown (teardown for the attached observer) functions? This might help protect non tg-veteran users from only calling one, resulting in no score recording, for example.

This isn't urgent, but it might be a nice feature to have.

**Comment by brtietz** [comment]
This has been handled with the implementation of craterEscape as an example.
