### ISSUE TITLE
tgBoxInfo uses inconsitent dimensions

### ISSUE THREAD

**Issue by brtietz** [NASA-Tensegrity-Robotics-Toolkit/NTRTsim#123]
When setting up tgBoxInfo a few months ago, I never did basic measurement tests like trying to make a cube. Having done that now, I realize that the dimensions are a little inconsistent - length actually gives the intended value, but specifying width and height results in 2x the desired dimensions due to these being the "half extents" of the collision shape. When convenient for users of these functions (i.e. tgCraterDeep), we should change line 109 of tgBoxInfo.cpp to divide all three variables by 2, or provide an alternate constructor (tgCubeInfo?) that makes the construction a little more intuitive (i.e. by making the origin the lower-front-left vertex, and the 2nd node the upper-back-right).

**Comment by apsabelhaus** [comment]
Closed as per issue #196. Let's keep the inconsistent width and height dimensions for now, since that's what everyone has been using. 

For future users who come to this issue - let's be sure to discuss it in the documentation for tgBox. See my thoughts in #196 .
