### ISSUE TITLE
Installing Boost using setup.sh

### ISSUE THREAD

**Issue by chiku00** [NASA-Tensegrity-Robotics-Toolkit/NTRTsim#166]

**Comment by PerryBhandal** [comment]
If you run setup.sh again and the setup completes, you should be good to go.

It's been a known issue for quite some time (see issue #2).

**Comment by PerryBhandal** [comment]
Oh, looks like you closed the issue just as I responded. I assume you noticed the same behavior when you ran it again!

In any case, if you run into any further problems, please feel free to open this issue again.

**Comment by chiku00** [comment]
Indeed. Mins after I posted it, I realized my mistake. Turns out I couldn't delete this issue altogether. Thank you PerryBhandal
