### ISSUE TITLE
Issues in building AppPrismModel

### ISSUE THREAD

**Issue by chiku00** [NASA-Tensegrity-Robotics-Toolkit/NTRTsim#167]
First of all, at least 6 header files along with their cpp files had to be moved to /../../core before I reached here:

![image](https://cloud.githubusercontent.com/assets/14135843/9701102/fb330508-5438-11e5-88d5-c42d31ee38e2.png)

I have no idea how to proceed from here on. It would be greatly appreciated if someone has a solution for this.

**Comment by PerryBhandal** [comment]
To build the applications you'll want to go into bin and run build.sh instead of directly compiling the source files. You can then execute the specific application to launch that structure in the simulator.

**Comment by chiku00** [comment]
Aha! Yes it did work. This had in fact occurred to me before, but that time, I had made a separate folder in src/examples with the codes and launched build.sh but nothing happened. I was under the impression that all the folders in the examples directory would be converted into an executable.
