### ISSUE TITLE
Trigonometric Functions not defined

### ISSUE THREAD

**Issue by chiku00** [NASA-Tensegrity-Robotics-Toolkit/NTRTsim#172]
I would like to bring to notice that Trigonometric Functions are not defined inside the script for a model. I believe, even without boost, trigonometric functions should be defined. Of course, the syntax for sine and cosine that I was using was 'sin()' and 'cos()', which might not be correct. If someone knows the correct function name, please let me know; feeding the nodal values manually for every small change I make is tiresome.
Refer to issue #171 for the code and other details.
Thank you

**Comment by brtietz** [comment]
Looking at the code from #171, it looks like you have an integer division
problem. What happens if you do 30.0/180.0?
